format_version: 3
pipelines:
  install-samples:
    group: citrus-samples
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/turing85/citrus-samples.git
        shallow_clone: false
        auto_update: true
        branch: master
        destination: citrus-samples
    stages:
      - install:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
          jobs:
            installTodoApp:
              timeout: 0
              elastic_profile_id: mvnContainer
              artifacts:
                - build:
                    source: citrus-samples
                    destination: ''
              tasks:
                - exec:
                    arguments:
                      - clean
                      - install
                      - -pl
                      - :citrus-sample-todo
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
  it-samples:
    group: citrus-samples
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      build:
        pipeline: install-samples
        stage: install
        name: install
    stages:
      - it-samples:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
          jobs:
            it-citrus-java-sample-annotation-config:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-annotation-config
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
            it-citrus-java-sample-behaviors:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-behaviors
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
            it-citrus-java-sample-binary:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-binary
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
            it-citrus-java-sample-camel-context:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-camel-context
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
            it-citrus-java-sample-disctionaries:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-dictionaries
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
            it-citrus-java-sample-docker:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-docker
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
            it-citrus-java-sample-kubernetes:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-kubernetes
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
            it-citrus-java-sample-reporting:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-reporting
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
            it-citrus-java-sample-rmi:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-rmi
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
            it-citrus-java-sample-jdbc:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-jdbc
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
            it-citrus-java-sample-jdbc-callable-statements:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-jdbc-callable-statements
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
            it-citrus-java-sample-ftp:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-ftp
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
            it-citrus-java-sample-scp:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-scp
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
  publish-samples:
    group: citrus-samples
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      build:
        pipeline: install-samples
        stage: install
        name: install
      it:
        pipeline: it-samples
        stage: it-samples
        name: it
    stages:
      - publish:
          fetch_materials: true
          artifacts:
            - build:
                source: citrus-samples/todo-app/target/
                destination: 'artifacts'
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
          jobs:
            publish:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: install-samples
                    stage: install
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - -lisa
                    command: ls
                    working_directory: citrus-samples
                    run_if: passed