format_version: 3
pipelines:
  install-citrus-samples:
    group: blogpage
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://turing85@bitbucket.org/turing85/blogpage.git
        shallow_clone: false
        auto_update: true
        branch: master
        destination: blogpage
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          build:
            timeout: 0
            elastic_profile_id: mvnContainer
            artifacts:
            - build:
                source: '**/target/classes/*'
                destination: classes
            tasks:
            - exec:
                arguments:
                - clean
                - compile
                command: mvn
                working_directory: blogpage
                run_if: passed
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          test:
            timeout: 0
            tabs:
              tests: testoutput
            elastic_profile_id: mvnContainer
            artifacts:
            - test:
                source: blogpage/blogpage-backend/blogpage-backend-model/target/site/jacoco/*
                destination: testoutput/coverage
            - test:
                source: blogpage/blogpage-backend/blogpage-backend-model/target/surefire-reports/*
                destination: testoutput/tests
            tasks:
            - exec:
                arguments:
                - clean
                - test
                command: mvn
                working_directory: blogpage
                run_if: passed
    - package:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          package:
            timeout: 0
            elastic_profile_id: mvnContainer
            artifacts:
            - build:
                source: blogpage/blogpage-backend/blogpage-backend-resources-thorntail/target/blogpage-backend-resources-thorntail-1.0-SNAPSHOT-thorntail.jar
                destination: deployment
            - build:
                source: blogpage/blogpage-backend/blogpage-backend-resources-thorntail/target/blogpage-backend-resources-thorntail-1.0-SNAPSHOT.war
                destination: deployment
            tasks:
            - exec:
                arguments:
                - clean
                - package
                command: mvn
                working_directory: blogpage
                run_if: passed
  it-samples:
    group: citrus-samples
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      build:
        pipeline: build-samples
        stage: installTodoApp
        name: build
    stages:
      - it-samples:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
          jobs:
            it-citrus-java-sample-annotation-config:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: build-samples
                    stage: installTodoApp
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-annotation-config
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed
            it-citrus-java-sample-behaviors:
              timeout: 0
              elastic_profile_id: mvnContainer
              tasks:
                - fetch:
                    is_file: false
                    source: citrus-samples
                    destination: ''
                    pipeline: build-samples
                    stage: installTodoApp
                    job: InstallTodoApp
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - verify
                      - -Dembedded
                      - -pl
                      - :citrus-java-sample-behaviors
                      - -Dmaven.repo.local=.m2
                    command: mvn
                    working_directory: citrus-samples
                    run_if: passed